# Graphite subgraph configuration

output_dir = "src/generated"
schema = "schema.graphql"

[[contracts]]
name = "ERC20"
abi = "abis/ERC20.json"

[[contracts]]
name = "ERC721"
abi = "abis/ERC721.json"
